version: "3.1"
services:
  rtsp-simple-server: #服务名
    image: aler9/rtsp-simple-server
    ports: 
    - 8554:8554
    - 1935:1935
    - 8888:8888
  ffmpeg:
    environment:
      - HOST_IP=${HOST_IP}
    image: jrottenberg/ffmpeg
    volumes:
       - ./data:/data
    command: -re -stream_loop -1 -i /data/1.mp4 -c copy -rtsp_transport tcp -f rtsp rtsp://${HOST_IP}:8554/mystream
    stdin_open: true
    tty: true
